version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  integration-test:
    build: ./tests/integration/
    command: pytest > pytests-integration-dev.log
    volumes:
      - ./tests/integration/:/opt/tests/integration/
    env_file:
      - ./.env.dev.test
    network_mode: host
    depends_on: 
      - web
